### ISSUE TITLE
In Collective Catalogue, searching by author institution not functioning

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#101]
If it's not a quick fix, would it be possible to simply remove that functionality in the interim? We've had a university annoyed by it, so it'd be good to get it either hidden or fixed. 

I'm imaginging it's related to Thoth updates?

**Comment by MartinPaulEve** [comment]
I think this is related to a recent change in the way that Thoth represents institutions and our data is now very bad on this, as the importer is not picking this up. This is also causing some of the problems in https://github.com/COPIM/open-book-collective/issues/52

Will have to rewrite the importer to use the new format.

We also need to have a conversation with Thoth -- if their API is not stable, then we will continue to hit these kind of bugs that cause us breakage.

**Comment by MartinPaulEve** [comment]
This is now fixed and working at https://openbookcollective.org/books/search/

**Comment by MartinPaulEve** [comment]
Raised related, but not causal, bug on Thoth https://github.com/thoth-pub/thoth/issues/518

**Comment by MartinPaulEve** [comment]
Bug triaged:

* Bug is in the sync feature from Thoth, not in search. Institutional affiliations were not being synced since the Thoth update.
* The sync function was only pulling the first 9999 entries from Thoth. There are actually more than 100k.
* If we add these manually in the try/catch block, the orphaned institution cleaner removes them.

**Comment by MartinPaulEve** [comment]
Fixed in https://github.com/COPIM/intrepid/commit/de0ac95448206db23679ff8c5fea20db133726a1
