### ISSUE TITLE
Create a shared catalogue

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#33]
As a publisher...
... I want my all my books to be discoverable directly via the platform
To increase access to my content

As a user
... I want to be able to search a catalogue featuring content from some or all of the publishers showcased on the platfrom
... To enable me to find content relevant to me / my users

**Comment by joedeville** [comment]
This one obviously has a history, but we do need to decide whether this is actually something we want or not -- either now or in future (I wonder if it's more one for the future, hence the label)?

**Comment by judith-fathallah** [comment]
I think its important to do this asap because this blog that Toby linked https://commonplace.knowledgefutures.org/pub/ff7gb1h2/release/1 suggests that librarians are really looking to support OA that is relevant to their institutions and courses. If not a full catalogue immediately then at least the site needs to be launched with a strong searchable system of categorization by collection, subject and themes
